_wandb:
    value:
        cli_version: 0.19.4
        code_path: code/Lunar_Lander_PPO/ppo.py
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.10.12
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
cuda:
    value: true
exp_name:
    value: ppo
gym_id:
    value: CartPole-v2
learning_rate:
    value: 0.00025
seed:
    value: 1
torch_deterministic:
    value: true
total_timesteps:
    value: 25000
track:
    value: true
wandb_entity:
    value: null
wandb_project_name:
    value: cleanRL
